### ISSUE TITLE
No obvious issues found during brief code review...

### ISSUE THREAD

**Issue by pamtbaau** [adamburton/listheme#1]
I have had a look at your theme and I haven't seen any obvious issues.  So, congrats with your first theme and congrats with your first GitHub respository...

What I do wonder about though is the need for your custom blueprint. But that's because I don't grasp the intention of 'fullurl', 'srcname' etc. on first sight.

**Comment by adamburton** [comment]
Hello pamtbaau,
thanks. I'm really glad that I've been able to get this far.

The custom blueprint is because I want to add extra information to each of my posts and to be able to present it as part of the blog listing.
So I'm making a news blog and I'm just posting links to other web sites as my blog, there's no original content. When I add a new page I include the name of the author of the original article, the name of the web site it is on `srcname`, the URL of the article `fullurl`, and the short url of the web site `srcurl`.

I then use these bits of information on the blog listing, so it says "article reposted from `{{ page.header.srcname }}`" and `"<a href="{{ page.header.fullurl }}">read the full article here</a>"`

that sort of thing.

Does that explain the need for this?

I hope you're well. bye
Adam

**Comment by pamtbaau** [comment]
That does explain it indeed.... 

As a hint,.. you might want to close this issue to mark it as done, sealed and delivered.... It will disappear from the list of issues that need to be dealt with.

**Comment by adamburton** [comment]
Thanks pamtbaau, bye
